# Basic
title: icome
subtitle: personal blog
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„å°ç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: icome
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: web/linux c++ å¼€å‘
url: "https://mmicome.github.com"

# Comment
comment:
    provider: duoshuo
    duoshuo:
     short_name: icome

# Social
social:
    weibo: 18195502756
    weixing: 813221186
    github: mmicome
    # google:
    mail: mmicome@gmail.com
    csdn: i-come

# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id: 1424d0cd963bd24ac7342f2ce515fb2d

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
#ga:
# id: UA-84134159-3
#  host: auto


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/mmicome/mmicome.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: ç•™è¨€, description: liuyan, url: '/liuyan'}
    - {title: èµ„æº, description: ziyuan, url: '/ziyuan'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}




# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"
